<header>
    <nav class="navbar navbar-expand-lg bg-primary" aria-label="Twelfth navbar example">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
                <ul class="navbar-nav">
                    <a class="nav-link link-warning active" aria-current="page" href="index.php">Accueil</a>

                    <a class="nav-link text-light" href="#">Catégories</a>

                    <a class="nav-link text-light" href="#">Profil</a>
                </ul>
            </div>
        </div>
    </nav>
</header>

<h1 class="accueil-title">Les derniers articles</h1>
<?php foreach ($articles as $article) : ?>
    <article class="recent-article">
        <h1 class="title-article"><?= $article->getTitle(); ?></h1>
        <small>Créé le <?= $article->getCreatedAt()->format('d/m/Y'); ?></small>
        <?php if ($article->getImage()) : ?>
            <img src="<?= $article->getImage() ?>" alt="" width="300px">
        <?php endif; ?>
        <p class="content-article"><?= mb_substr($article->getContent(), 0, 100) ?> [...]</p>
        <div>
            <p class="category-article">@TODO</p>
            <a class="read-more" href="article.php?id=<?= $article->getIdArticle() ?>">Lire la suite</a>
        </div>
    </article>
<?php endforeach; ?>

<footer></footer>