<header>
    <nav class="navbar navbar-expand-lg bg-primary" aria-label="Twelfth navbar example">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
                <ul class="navbar-nav">
                    <a class="nav-link text-light" aria-current="page" href="index.php">Accueil</a>

                    <a class="nav-link text-light" href="#">Catégories</a>

                    <a class="nav-link text-light" href="#">Profil</a>
                </ul>
            </div>
        </div>
    </nav>
</header>



<article class="all-article">
    <h1 class="all-title-article"><?= $articlesId['title']; ?></h1>
    <?php if ($articlesId['image']) : ?>
        <img src="<?= $articlesId['image'] ?>" alt="" width="500px">
    <?php endif; ?>
    <p class="all-content-article"><?= $articlesId['content'] ?></p>
</article>