<article class="all-article">
    <h1 class="all-title-article"><?= $articlesId->getTitle(); ?></h1>
    <p class="category-article"><?= $articlesId->getCategoryName() ?></p>
    <?php if ($articlesId->getImage()) : ?>
        <img src="<?= asset('images/' . $articlesId->getImage()) ?>" alt="" width="500px">
    <?php endif; ?>
    <p class="all-content-article"><?= $articlesId->getContent(); ?></p>
</article>

<section>
    <h2 style="text-align: center; margin-top: 30px;">Commentaires</h2>
    <form method="POST" action="<?= constructUrl('/article', ['id' => $articlesId->getIdArticle()]); ?>" class="d-flex flex-column align-items-center mt-4">
        <legend style="text-align: center;">Ajouter un commentaire</legend>
        <div class="mb-3 w-50">
            <label for="nickname" class="form-label">Pseudo</label>
            <input type="text" name="nickname" class="form-control" id="nickname" placeholder="Votre pseudo">
            <?php if (isset($errors['nickname'])) : ?>
                <p class="error"><?= $errors['nickname'] ?></p>
            <?php endif; ?>
        </div>
        <div class="mb-3 w-50">
            <label for="content" class="form-label">Commentaire</label>
            <textarea class="form-control" name="content" id="content" rows="5"></textarea>
            <?php if (isset($errors['content'])) : ?>
                <p class="error"><?= $errors['content'] ?></p>
            <?php endif; ?>
        </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>

    <?php if (empty($comments)) : ?>
        <p style="text-align: center; margin-top: 30px;">Soyez le premier à ajouter un commentaire !</p>
    <?php else : ?>
        <?php foreach ($comments as $comment) : ?>
            <div class="comment-block">
                <h4 class="title-comment" style="text-align: center;">Ajouté par <?= $comment->getNickname(); ?> le <?= $comment->getFormattedCreatedAt(); ?></h4>
                <p class="comment" style="text-align: center;"><?= $comment->getContent(); ?></p>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>


</section>

<footer></footer>