<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $pageTitle ?></title>
    <link rel="stylesheet" href="<?= asset('css/style.css') ?>">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" aria-label="Twelfth navbar example">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample10" aria-controls="navbarsExample10" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-md-center" id="navbarsExample10">
                    <ul class="navbar-nav">
                        <a class="nav-link link-warning active" aria-current="page" href="<?= constructUrl('home'); ?>">Accueil</a>
                        <a class="nav-link text-light" href="<?= constructUrl('contact'); ?>">Contact</a>
                        <?php if ((new App\Service\UserSession())->getUser()) : ?>
                            <a class="nav-link text-light" href="<?= constructUrl('logout'); ?>">Déconnexion</a>
                        <?php else : ?>
                            <a class="nav-link text-light" href="<?= constructUrl('login'); ?>">Connexion</a>
                            <a class="nav-link text-light" href="<?= constructUrl('signup'); ?>">Créer un compte</a>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main>
        <!-- Message flash -->
        <?php if (isset($flashMessage) && $flashMessage) : ?>
            <p class="success"><?= $flashMessage ?></p>
        <?php endif; ?>

        <!-- Contenu de la page -->
        <?php include $template . '.phtml'; ?>
    </main>
</body>

</html>