<section>
    <h2 style="text-align: center; margin-top: 30px;">Contact</h2>
    <form id="contact-form" method="POST" action="<?= constructUrl('ajax-send-contact-form') ?>" class="d-flex flex-column align-items-center mt-4">
        <div class="mb-3 w-50">
            <label for="email" class="form-label">Email</label>
            <input type="text" name="email" class="form-control" id="email">
        </div>
        <div class="mb-3 w-50">
            <label for="subject" class="form-label">Sujet</label>
            <input type="text" name="subject" class="form-control" id="subject">
        </div>
        <div class="mb-3 w-50">
            <label for="content" class="form-label">Message</label>
            <textarea class="form-control" name="content" id="content" rows="5"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Envoyer</button>
    </form>
</section>

<script src="<?= asset('js/contact.js') ?>"></script>